MyEpoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from epoc_app.views import welcome

admin.site.site_header = "Portal SPO2"
admin.site.site_title = "Portal SPO2"
admin.site.index_title = "Bienvenido al sistema de registro de SPO2 "

urlpatterns = [
    path('epoc/', include('epoc_app.urls')),
    path('chat/', include('chat.urls')),
    path('login/', include('accounts.urls'), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("", welcome, name="welcome"), 
]

chat/urls.py
from django.urls import path

from . import views 

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('<str:uuid>/', views.room, name='room'),
    path('<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

chat/models.py
from django.db import models

from accounts.models import User

class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    ## models.SET_NULL means that when user is deleted the message remains but without a connection

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'
    

class Room(models.Model):
    WAITING = 'waiting'
    ATTENDED = 'attended'
    CHOICES_STATUS = {
        (WAITING, 'Waiting'),
        (ATTENDED, 'Attended'),
    }

    uuid = models.CharField(max_length=255)     #Unique id for fronted (js id)
    client = models.CharField(max_length=255)   #User on frontend
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True) #Blank in case no message
    url = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

templates/partials/chat_bubble.html
<div id="chat" class="max-w-[350px] fixed right-2 bottom-2 p-4 bg-white border border-gray-300 rounded-xl">
    <div id="chat_icon">
        <button id="chat_open" class="w-[50px] flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="text-blue-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
              </svg>              
        </button>
    </div>

    <!-- mb-4 (margin botton) space below 
    p-4 space inside -->

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p> Chat with your doctor, write something below...</p>
        </div>
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Escribe un mensaje">
        <button id="chat_message_submit" class="p-2 px-6 bg-blue-600 text-white rounded-xl">Send</button>
    </div>

</div>

templates/partials/room_lists.html
<div class="grid grid-cols-4 gap-4">
    {% for room in rooms %}
        <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-blue-100 
                                    {% elif room.status == 'attended' %}bg-emerald-100 
                                    {% else %} bg-gray-100 {% endif %}">
            <h3 class="mb-4 text-lg"> Chat</h3>
            
            <p>
                <b>ID: </b> {{ room.uuid }} <br>
                <b>Name: </b> {{ room.client }} <br>
                <b>Status: </b> {{ room.get_status_display }} <br>
                <b>Doctor: </b> {% firstof room.agent.name 'None yet...' %}
            </p>

            <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-emerald-800 text-white rounded-xl">Join</a>

            <a href="{% url 'chat:delete_room' room.uuid %}"class="mt-4 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Delete</a>
        </div>
    {% endfor %}
</div>