MyEpoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from epoc_app.views import welcome

admin.site.site_header = "Portal SPO2"
admin.site.site_title = "Portal SPO2"
admin.site.index_title = "Bienvenido al sistema de registro de SPO2 "

urlpatterns = [
    path('epoc/', include('epoc_app.urls')),
    path('chat/', include('chat.urls')),
    path('login/', include('accounts.urls'), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("", welcome, name="welcome"), 
]

chat/urls.py
from django.urls import path

from . import views 

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('<str:uuid>/', views.room, name='room'),
    path('<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

accounts/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone
from secret_settings import *
from encrypted_fields.fields import EncryptedEmailField

class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(name=name, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    PATIENT = 'patient'
    MEDIC = 'medic'

    ROLES_CHOICES = (
        (PATIENT, 'Patient'),
        (MEDIC, 'Medic'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = EncryptedEmailField(max_length=256)
    name = models.CharField(max_length=255, unique=True, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=PATIENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'name'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['role']

chat/models.py
from django.db import models

from accounts.models import User

class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    ## models.SET_NULL means that when user is deleted the message remains but without a connection

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'
    

class Room(models.Model):
    WAITING = 'waiting'
    ATTENDED = 'attended'
    CHOICES_STATUS = {
        (WAITING, 'Waiting'),
        (ATTENDED, 'Attended'),
    }

    uuid = models.CharField(max_length=255)     #Unique id for fronted (js id)
    client = models.CharField(max_length=255)   #User on frontend
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True) #Blank in case no message
    url = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

templates/add_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
<title>WETMOS - Add user</title>
{% endblock %}

{% block content %}
    <h1 class="mt-4 px-4 mb-6 text-4xl"> Add user</h1>

    <form method="post" action="." class="px-4">
        {% csrf_token %}

        {{ form.as_p}}

        <button class="mb-4 mt-6 inline-block py-2 px-6 bg-blue-600 text-white rounded-xl"> Add User</a>
    </form>

{% endblock %}

templates/admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
<title>WETMOS - Chats and users</title>
{% endblock %}

{% block content %}
    {% if messages %}
    <div class="message mt-2 px-4 mb-6 p-6 bg-gray-800 text-white rounded-xl">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    <h1 class="mt-4 px-4 text-4xl"> Settings</h1>

    {% if perms.user.add_user %}
        <div class="px-4 mt-4">
            <h2 class="mb-4 text-lg">Users</h2>

            <a href="{% url 'add_user' %}" class="inline-block py-2 px-6 bg-blue-600 text-white rounded-xl"> Add User</a>

            <div class="mt-6"> 
                {% for user in users %}
                    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">
                        <p class="px-2">
                            {{user.name}} 
                        </p>
                        <p class="px-2"> 
                            {{user.email}}
                        </p>
                        <p class="px-2"> 
                            {{user.get_role_display}}
                        </p>
                        <p class="px-2 text-right">
                            <a href="{% url 'edit_user' user.pk%}" class="underline"> Edit</a>
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>

        <hr class="my-6">    

        <div class="px-4 mt-4">
            <h2 class="mb-4 text-lg"> Chats </h2>
    
            {% include 'partials/room_lists.html' %}
        </div>
        
    {% endif %}

{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" type="image/png" href="{% static 'icon.ico' %}"/>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title %}
        {% endblock%}
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'welcome' %}">WETMOS</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>

            <ul class="navbar-nav ms-auto my-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                        {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                        {% endif%}

                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    {% if request.user.is_authenticated %}
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Menu</div>
                            <a class="nav-link" href="{% url 'welcome' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Homepage
                            </a>

                            {% if request.user.role == 'patient'%}
                            <a class="nav-link" href="{% url 'detail' request.user.name %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-heartbeat"></i></div>
                                Overview
                            </a>
                            {% else %}
                            <a class="nav-link" href="{% url 'monitor' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Monitor patients
                            </a>
                            <a class="nav-link" href="{% url 'admin' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-circle-user"></i></div>
                                Chats and users
                            </a>
                            <a class="nav-link" href="{% url 'admin:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-gears"></i></div>
                                Admin
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">User:</div>
                        {{ user.name }} ({{user.role}})
                        
                    </div>

                    {% else %}
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Menu</div>
                            <a class="nav-link" href="{% url 'welcome' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Homepage
                            </a>
                        </div>
                    </div>
                    {% endif%}

                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {% block content%}
                    {% endblock %}
                </main>

                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; WETMOS 2023</div>
                        </div>
                    </div>
                </footer>
            </div>
            {% block scripts %}
            {% endblock %}
        </div>
        <script src="{% static 'js/scripts.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}



{% block scripts %}
    <script src="{% static 'js/dashboard.js' %}" defer></script>
{% endblock scripts%}

{% block content%}
<p id="app">{{ text }}</p>
{% endblock content %}

templates/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
<title>WETMOS - Edit user</title>
{% endblock %}

{% block content %}
    <h1 class="px-4 mt-4 mb-6 text-4xl"> Edit user</h1>

    <form method="post" action="." class="px-4">
        {% csrf_token %}

        {{ form.as_p}}

        <button class="mb-2 mt-6 inline-block py-2 px-6 bg-blue-600 text-white rounded-xl"> Save changes</a></button>
    </form>


    <a href="{% url 'delete_user' user.pk %}"class="mx-4 mt-2 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Delete</a>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>WETMOS - Monitor</title>
{% endblock %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Patients</h1>
    <div class="card mb-4">
        <div class="card-body">
            General information of registered patients
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Patients
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>SpO2 (%)</th>
                        <th>Flow (L/min)</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                    <tr>
                        <td>{{ patient.name }}</td>
                        <td>{{ patient.spo2 }}</td>
                        <td>{{ patient.flow }}</td>
                        <td>
                            <a href="{% url 'detail' patient.id %}" class="btn btn-primary btn-sm" role="button">Monitor</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts%}
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatables-simple-demo.js'%}"></script>
{% endblock %}

templates/monitor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>WETMOS - Monitor</title>
{% endblock %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Patients</h1>
    <div class="card mb-4">
        <div class="card-body">
            General information of registered patients
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Patients
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>SpO2 (%)</th>
                        <th>Flow (L/min)</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                    <tr>
                        <td>{{ patient.name }}</td>
                        <td>{{ patient.spo2 }}</td>
                        <td>{{ patient.flow }}</td>
                        <td>
                            <a href="{% url 'detail' patient.name %}" class="btn btn-primary btn-sm" role="button">Monitor</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts%}
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatables-simple-demo.js'%}"></script>
{% endblock %}

templates/pat_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>WETMOS - Datos</title>
{% endblock %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Patient's details</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Overview</li>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-secondary text-white mb-4">
                <div class="card-body" style="font-size: 30px";>{{patient.name}}</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link">Patient</a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div id='spo-container' class="card-body" style="font-size: 30px";>0</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link">SpO2</a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body" style="font-size: 30px";>{{command.flow}} L/min</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link">Flow</a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div id='alert-color' class="card bg-primary text-white mb-4">
                <div id='alert-container' class="card-body" style="font-size: 30px";>None yet</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link">Alarms</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {% if request.user.role == 'medic' %}
        <div class="col-xl-6">
        {%else%}
        <div class="col-xl-12">
        {% endif %}
            <div class="card mb-4">
                <div id="spo2_tab" class="card-header">
                    <i class="fas fa-chart-area me-1"></i>
                    Patient's history 
                </div>
                <div class="card-body">
                    <canvas id="chart_SPO2" data-url="{% url 'spo2-chart' patient.id%}"></canvas>
                </div>
                <div class="card-body">
                    <canvas id="chart_FLOW" data-url="{% url 'spo2-chart' patient.id%}"></canvas>
                </div>
            </div>
        </div>
        
        {% if request.user.role == 'medic' %}
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-bar me-1"></i>
                    Control Flow
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.patient.label_tag }} {{ form.patient }}
                        {{ form.patient.errors }}
                        <br>
                        {{ form.flow.label_tag }} {{ form.flow }}
                        {{ form.flow.errors }}
                        <br>
                        <p></p>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div> 
        {% endif %}
    </div>
</div>  
{% endblock %}

 
{% block scripts %}                      
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>  
    var interval = setInterval(function () {
    var lastValue;
    var $SpoChart = $("#chart_SPO2");
    var $FlowChart = $("#chart_FLOW");
    var $SpoContainer = $("#spo-container");
    var $AlertContainer = $("#alert-container");
    var $AlertColor = $("#alert-color");
    
    $.ajax({
        url: $SpoChart.data("url"),
        success: function (data) {
        lastValue = data.data[data.data.length - 1];
        console.log(lastValue);
        $SpoContainer.text(lastValue);
        

        if (lastValue >= 85) {
            $AlertContainer.text("Safe");
            $AlertColor.removeClass("bg-danger").addClass("bg-primary");
        } else {
            $AlertContainer.text("Danger: SpO2");
            $AlertColor.removeClass("bg-primary").addClass("bg-danger");
        }

        var ctx = $SpoChart[0].getContext("2d");
        new Chart(ctx, {
            type: 'line',
            data: {
            labels: data.labels,
            datasets: [{
                label: 'SpO2',
                lineTension: 0.3,
                backgroundColor: "rgba(2,117,216,0.2)",
                borderColor: "rgba(2,117,216,1)",
                pointRadius: 5,
                pointBackgroundColor: "rgba(2,117,216,1)",
                pointBorderColor: "rgba(255,255,255,0.8)",
                pointHoverRadius: 5,
                pointHoverBackgroundColor: "rgba(2,117,216,1)",
                pointHitRadius: 50,
                pointBorderWidth: 2,
                data: data.data
            }]          
            },
            options: {
            responsive: true,
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Patient\'s SpO2'
            }
            }
        });

        var flow_ctx = $FlowChart[0].getContext("2d");
        new Chart(flow_ctx, {
            type: 'line',
            data: {
            labels: data.labels,
            datasets: [{
                label: 'Flow',
                lineTension: 0.3,
                backgroundColor: "rgba(31,120,50,0.2)",
                borderColor: "rgba(31,120,50,1)",
                pointRadius: 5,
                pointBackgroundColor: "rgba(31,120,50,1)",
                pointBorderColor: "rgba(255,255,255,0.8)",
                pointHoverRadius: 5,
                pointHoverBackgroundColor: "rgba(2,117,216,1)",
                pointHitRadius: 50,
                pointBorderWidth: 2,
                data: data.flow
            }]          
            },
            options: {
            responsive: true,
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Valve\'s flow'
            }
            }
        });
        }
    });
    },4000);
</script>
{% endblock %}

templates/room.html
{% extends 'base.html' %}

<!-- {% load chatextras %} -->
{% load static %}

{% block title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
<title>WETMOS - Chat with {{room.client}}</title>
{% endblock %}

{% block content %}
    <h1 class="mt-2 px-4 text-4xl">
        Room "{{ room.uuid }}"
    </h1>

    <hr class="px-4 my-6">

    <p class="px-4 mb-6">
        <b>Name: </b> {{room.client}}<br>
        <b>Started: </b> {{room.created_at|timesince}} ago<br>
        <b>Status: </b> {{room.get_status_display}}<br>
        <b>Page: </b> {{room.url}} <br>
        <b>Doctor: </b> {% firstof room.agent.name 'None yet...' %}
    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mx-4 mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{%endif%}">
                {% if not message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}
            
                <div>
                    <div class="p-3 rounded-xl {% if message.created_by %} bg-blue-600 text-white {%else%}bg-gray-300{%endif%}">
                        <p class="text-sm">{{message.body}} </p>
                    </div>

                    <span class="text-xs text-gray-500 leading-none">
                        {{message.created_at|timesince}} ago
                    </span>
                </div>
                
                {% if message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}

            </div>
        {% endfor %}
    </div>

    {% if room.status == 'attended' %}
    <input type="text" name="body" id="chat_message_input" class="w-4/5 mx-4 px-4 mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Escribe un mensaje">
    <button id="chat_message_submit" class="mx-4 mb-6 p-2 px-4 px-6 bg-blue-600 text-white rounded-xl">Send</button>
    {% endif%}

{% endblock %}


{% block scripts %}
    {% if room.status == 'attended' %}
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.name|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}
        <script src="{% static 'js/main_admin.js' %}">
        </script>
    {% endif %}
{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
<title>WETMOS - Home</title>
{% endblock %}


{% block content %}
<div class="mt-12 py-12 px-8 grid grid-cols-1 gap-4 items-center border border-rose-200 rounded-xl">

    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl">

        <div class="col-span-4">
            <h1 class="mb-8 text-3xl">Welcome to WETMOS</h1>

            <h2 class="text-lg text-gray-500">
                WETMOS is a domestic low-flow oxygen therapy device for COPD (Chronic Obstructive Pulmonary Disease) that
                allows healthcare professionals to monitor patients through telemedicine based on their
                SpO2 levels.
            </h2>
            
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-blue-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 19.5v-.75a7.5 7.5 0 00-7.5-7.5H4.5m0-6.75h.75c7.87 0 14.25 6.38 14.25 14.25v.75M6 18.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
            </svg>
              
            
            <h3 class="mb-4 text-xl text-gray-800">Connect your device</h3>

            <p class="text-gray-500">Connect WETMOS to a Wi-Fi network in order to start transmitting your current status remotely.  </p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-blue-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
              </svg>            
              
              
            
            <h3 class="mb-4 text-xl text-gray-800">Create your credentials</h3>

            <p class="text-gray-500">Set up your account with the help of a doctor in order to track changes on your treatment.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-blue-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Chat with your doctor</h3>

            <p class="text-gray-500">In case of any doubts or emergencies, contact your doctor through the built-in chat in our web page.</p> 
        </div>
    </div>
    {% if request.user.is_authenticated %}
        {% if request.user.role == 'patient'%}
            {% include 'partials/chat_bubble.html'%}
        {% endif %}
    {% endif %}
    
{% endblock %}

{% block scripts %}
{% if request.user.is_authenticated %}
{% if request.user.role == 'patient'%}
{{ request.user.name|json_script:'user_name' }}
<script src="{% static 'js/main.js' %}"></script>
{% endif %}
{% endif %}
{% endblock %}